---
- name: Pull and Run docker image of divyeshradadiya/caldev
  hosts: all
  tasks:
    - name: Pull divyeshradadiya/caldev image
      docker_image:
          name: divyeshradadiya/caldev
          source: pull
        
